import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import Logo from "~/svg/Logo";
import Underline from "~/svg/Underline";
import { IoChevronDownOutline } from "@react-icons/all-files/io5/IoChevronDownOutline";
import Image from "next/image";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Tailored Cv</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="min-h-screen">
        <header
          className={
            "sticky top-0 z-50 border-b border-solid border-gray-300 bg-white py-1 shadow-2xl"
          }
        >
          <div className={"m-auto flex max-w-7xl justify-between px-4"}>
            <div className={"flex items-center gap-2 fill-primary-600"}>
              <Logo className="h-12 w-12" />
              <p className={"text-lg font-bold"}>Tailored cv</p>
            </div>
            <Link
              href={"/"}
              className={
                "rounded-full bg-primary-600 p-3 text-base font-bold text-white hover:bg-primary-700"
              }
            >
              Join the wait list
            </Link>
          </div>
        </header>
        <div className={"bg-secondary-700 py-16 text-white"}>
          <div
            className={
              "m-auto flex max-w-3xl flex-col items-center justify-center gap-10"
            }
          >
            <h1
              className={
                "flex flex-wrap justify-center gap-3 text-5xl font-bold"
              }
            >
              <span>
                A personalized
                <Underline className={"w-full fill-primary-600"} />
              </span>{" "}
              resume everytime
            </h1>
            <h3 className={"text-center text-xl"}>
              The ultimate app designed to elevate your job application game.
              Empowers you to create personalized resumes and cover letters{" "}
              <span
                className={
                  "relative z-10 whitespace-nowrap bg-transparent px-1 font-bold text-black"
                }
              >
                <div
                  className={"absolute inset-0 -z-10 -rotate-1 bg-green-400"}
                />
                for each specific position
              </span>{" "}
              you apply to.
            </h3>
            <Link
              href={"/"}
              className={
                "rounded-full bg-primary-600 p-3 text-lg font-bold text-white hover:bg-primary-700"
              }
            >
              Join the wait list
            </Link>
          </div>
        </div>
        <section className={"m-auto max-w-7xl p-4 py-16"}>
          <h2 className={"mb-4 text-center text-4xl font-bold"}>
            Effortlessly frame your profile for the role.
          </h2>
          <p className={"mb-2 text-center text-base"}>
            {" "}
            Gone are the days of manually customizing your resume and struggling
            to highlight the most relevant skills and experiences for a
            particular job.
          </p>
          <p className={"text-center text-base"}>
            {" "}
            With the help of Chat-GPT we analyze your background and generate a
            custom resume and cover letter, emphasizing relevant aspects.
            Present yourself as an ideal candidate with optimized content,
            streamlined structure, and enhanced readability for a polished final
            product.
          </p>
        </section>
        <section className={"bg-secondary-50 py-16"}>
          <div className={"m-auto flex max-w-7xl flex-wrap gap-4 px-4"}>
            <div className={"flex flex-1 flex-col gap-4"}>
              <div className={"relative w-fit"}>
                <h2 className={"relative z-10 text-3xl font-bold"}>
                  {" "}
                  Your past
                </h2>
                <div
                  className={
                    "absolute bottom-0 right-0 h-1 w-20 -rotate-2 rounded-full bg-primary-500"
                  }
                />
              </div>
              <h3 className={"text-xl font-bold"}>
                Tell us about you and your experiences
              </h3>
              <p className={"text-base"}>
                To ensure the utmost accuracy and effectiveness, we request that
                you provide us with a detailed, long-form resume. This
                comprehensive document allows our app to fully analyze your
                professional journey, skills, and achievements. By having access
                to a comprehensive overview of your background, we then can
                tailor your resume and cover letter to perfectly match your
                qualifications with the position you're targeting.
              </p>
            </div>

            <div
              className={
                "flex max-h-[350px] flex-1 flex-col gap-4 overflow-hidden rounded-2xl bg-gray-50 p-4 shadow-xl"
              }
            >
              <div
                className={
                  "flex flex-col gap-4 rounded-2xl bg-white p-4 shadow-sm "
                }
              >
                <h3 className={"text-lg font-bold text-primary-600"}>
                  Work experience
                </h3>
                <div className={"relative rounded-xl bg-gray-50 p-4 "}>
                  <p className={"mb-4 text-base font-bold"}>
                    Software Intern - Apple
                  </p>
                  <p className={"text-sm "}>2012-2014</p>
                  <div
                    className={
                      "absolute inset-y-0 right-0 flex items-center pr-4"
                    }
                  >
                    <IoChevronDownOutline className={"h-6 w-6"} />
                  </div>
                </div>
                <div className={"relative rounded-xl bg-gray-50 p-4 "}>
                  <p className={"mb-4 text-base font-bold"}>
                    Senior Software Architect - Netflix
                  </p>
                  <p className={"text-sm "}>2014-2020</p>
                  <div
                    className={
                      "absolute inset-y-0 right-0 flex items-center pr-4"
                    }
                  >
                    <IoChevronDownOutline className={"h-6 w-6"} />
                  </div>
                </div>
              </div>
              <div className={"rounded-2xl bg-white p-4 shadow-sm"}>
                <h3 className={"text-lg font-bold text-primary-600"}>
                  Education
                </h3>
              </div>
            </div>
          </div>
        </section>
        <section className={"py-16 "}>
          <div className={"m-auto flex max-w-7xl flex-wrap gap-4 px-4"}>
            <div className={"flex flex-1 flex-col gap-4"}>
              <div className={"relative w-fit"}>
                <h2 className={"relative z-10 text-3xl font-bold"}>
                  The position
                </h2>
                <div
                  className={
                    "absolute bottom-0 right-2 h-1 w-40 rotate-3 rounded-full bg-primary-500"
                  }
                />
              </div>
              <p>
                Provide us with the position description, including the
                requirements and any additional "nice to have" qualifications
              </p>
            </div>
            <div
              className={
                "flex max-h-[350px] flex-1 flex-col gap-4 overflow-hidden rounded-2xl bg-gray-50 p-4 shadow-xl"
              }
            >
              <div
                className={
                  "flex flex-col gap-4 rounded-2xl bg-white p-4 shadow-sm "
                }
              >
                <h3 className={"text-lg font-bold text-primary-600"}>
                  Position Description
                </h3>
                <div
                  className={
                    "overflow-y-scroll rounded-md border border-solid border-black bg-gray-50 p-2"
                  }
                >
                  Requirements
                  <br />
                  Minimum of 2+ Years within a relevant role
                  <br />
                  Familiarity with at least one: Vue, React, Angula
                  <br />
                  Responsibilities
                  <br />
                  Develop mobile-first frontends in VueJS
                  <br />
                  Focus on performance and user experience
                  <br />
                  Create frontends for the backend management systems
                  <br />
                </div>
                <div className={"flex justify-end"}>
                  <div
                    className={
                      "w-fit rounded-full bg-primary-600 p-3 text-base font-bold text-white"
                    }
                  >
                    Submit
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>
        <section className={"bg-secondary-50 py-16"}>
          <div className={"m-auto flex max-w-7xl gap-4 px-4"}>
            <div className={"flex flex-1 flex-col gap-4 "}>
              <div className={"relative w-fit"}>
                <h2 className={"relative z-10 text-3xl font-bold"}>
                  Get a tailored resume and cover letter
                </h2>
                <div
                  className={
                    "absolute bottom-0 right-2 h-1 w-40 -rotate-2 rounded-full bg-primary-500"
                  }
                />
              </div>
              <p>
                Retrieve a customized resume and cover letter, precisely
                highlighting the most relevant aspects of your background for
                that specific position. It optimizes the content, streamlines
                the structure, and enhances the overall readability, resulting
                in a polished and professional final product.
              </p>
              <p>
                You can easily modify the content, reorganize sections, or add
                specific details to ensure your application reflects your unique
                strengths and accomplishments.
              </p>
            </div>
            <div className={"flex-1"}>
              <Image
                src={"/cv.png"}
                width={250}
                height={200}
                alt={"Cv image"}
              />
            </div>
          </div>
        </section>
        <div className={"m-auto max-w-7xl px-4 pt-16"}>
          <h3 className={"text-3xl font-bold"}>Download and apply</h3>
        </div>
        <footer className={"bg-primary-900"}>
          <div
            className={
              "m-auto flex max-w-7xl justify-between gap-4 px-4 py-16 text-white"
            }
          >
            <div className={"flex flex-col gap-6"}>
              <div className={"flex items-center gap-2 fill-primary-600"}>
                <Logo className="h-12 w-12 fill-white" />
                <p className={"text-lg font-bold"}>Tailored cv</p>
              </div>
              <p>
                TailoredCv helps increase your chances of getting the dream job
              </p>
            </div>
            <div className={"flex flex-col gap-6"}>
              <h4 className={"text-xl uppercase"}>Product</h4>
            </div>
            <div className={"flex flex-col gap-6"}>
              <h4 className={"text-xl uppercase"}>Support</h4>
            </div>
          </div>
        </footer>
      </main>
    </>
  );
};

export default Home;
